// SPDX-License-Identifier: AGPL-3.0-or-later
export const SOURCE_IDS=['ibge','inep','cnes','pncp','transferegov','obrasgov','other'];
export const STATUS_IDS=['completed','partial','failed','running','unknown'];
export const STATE_IDS='AC AL AP AM BA CE DF ES GO MA MT MS MG PA PB PR PE PI RJ RN RS RO RR SC SP SE TO'.split(' ');
const labels={ibge:'IBGE',inep:'Inep',cnes:'CNES',pncp:'PNCP',transferegov:'Transferegov',obrasgov:'Obrasgov'};
export const coverageMessages={
  'pt-BR':{coverageTitle:'Conheça os dados disponíveis',coverageIntro:'Veja o que esta instalação carregou e acompanhe suas tentativas de importação.',coverageScope:'Registros carregados não certificam cobertura nacional, atualização da fonte ou atendimento disponível. Uma falha de importação não significa que o serviço deixou de existir.',coverageRefresh:'Atualizar cobertura',coverageRetry:'Tentar cobertura novamente',coverageError:'Não foi possível atualizar a cobertura. As informações anteriores, quando exibidas, permanecem identificadas.',coveragePlaces:'Lugares no catálogo',coverageLocated:'Com posição no mapa',coverageUnlocated:'Sem posição confirmada',coverageResources:'Recursos cadastrados',coverageSources:'Fontes incorporadas',coverageLoaded:'Há dados carregados',coverageNotLoaded:'Sem dados carregados',coverageOther:'Outras fontes',coverageNoAttempt:'Sem tentativa registrada',coverageLastAttempt:'Última tentativa',coverageReference:'Referência do dado',coverageAttemptDate:'Data da tentativa',coverageNeverComplete:'Sucesso de importação não é certificado de completude da fonte.',coverageTerritory:'Catálogo por território',coverageSourceFilter:'Fonte do catálogo',coverageStateFilter:'Estado do catálogo',coverageState:'UF',coverageAll:'Todos',coverageNoPartitions:'Nenhum registro carregado neste recorte.',coverageImports:'Histórico de importações',coverageImportSource:'Fonte das importações',coverageImportStatus:'Resultado das importações',coverageImportsError:'O histórico não carregou. A cobertura acima continua disponível.',coverageImportsRetry:'Tentar histórico novamente',coverageImportsEmpty:'Nenhuma tentativa registrada neste filtro.',coverageCompleted:'Concluída',coveragePartial:'Parcial',coverageFailed:'Não publicada',coverageRunning:'Em andamento',coverageUnknown:'Cadastro oficial',coverageRead:'Registros lidos',coverageCreated:'Registros criados',coverageUpdated:'Registros alterados',coverageFailedNote:'Os registros anteriores foram preservados; os contadores desta tentativa não representam novos dados publicados.',coverageHistoryPage:'Página do histórico',coverageObservedAt:'Consulta desta instalação',coverageRecords:'Registros',coverageUnknownState:'UF não identificada',coverageDocumentation:'Documentação da fonte',coverageMore:'Detalhar por UF'},
  en:{coverageTitle:'Understand the available data',coverageIntro:'See what this installation has loaded and review its import attempts.',coverageScope:'Loaded records do not certify national coverage, source freshness or available services. An import failure does not mean a service ceased to exist.',coverageRefresh:'Refresh coverage',coverageRetry:'Retry coverage',coverageError:'Coverage could not be refreshed. Previously shown information remains identified.',coveragePlaces:'Places in the catalog',coverageLocated:'With map coordinates',coverageUnlocated:'Without confirmed coordinates',coverageResources:'Registered resources',coverageSources:'Included sources',coverageLoaded:'Data is loaded',coverageNotLoaded:'No data loaded',coverageOther:'Other sources',coverageNoAttempt:'No recorded attempt',coverageLastAttempt:'Last attempt',coverageReference:'Data reference',coverageAttemptDate:'Attempt date',coverageNeverComplete:'A successful import does not certify source completeness.',coverageTerritory:'Catalog by territory',coverageSourceFilter:'Catalog source',coverageStateFilter:'Catalog state',coverageState:'State',coverageAll:'All',coverageNoPartitions:'No records loaded for these criteria.',coverageImports:'Import history',coverageImportSource:'Import source',coverageImportStatus:'Import outcome',coverageImportsError:'Import history could not be loaded. Coverage remains available above.',coverageImportsRetry:'Retry history',coverageImportsEmpty:'No recorded attempts match these filters.',coverageCompleted:'Completed',coveragePartial:'Partial',coverageFailed:'Not published',coverageRunning:'In progress',coverageUnknown:'Official record',coverageRead:'Records read',coverageCreated:'Records created',coverageUpdated:'Records updated',coverageFailedNote:'Previously loaded records were preserved; this attempt does not represent newly published data.',coverageHistoryPage:'History page',coverageObservedAt:'Installation queried at',coverageRecords:'Records',coverageUnknownState:'State not identified',coverageDocumentation:'Source documentation',coverageMore:'Details by state'},
  es:{coverageTitle:'Conozca los datos disponíveis',coverageIntro:'Vea lo que esta instalación ha cargado y revise sus intentos de importación.',coverageScope:'Los registros cargados no certifican cobertura nacional, actualidad de la fuente ni atención disponible. Una importación fallida no significa que el servicio haya dejado de existir.',coverageRefresh:'Actualizar cobertura',coverageRetry:'Reintentar cobertura',coverageError:'No se pudo actualizar la cobertura. La información anterior, cuando se muestra, sigue identificada.',coveragePlaces:'Lugares del catálogo',coverageLocated:'Con posición en el mapa',coverageUnlocated:'Sin posición confirmada',coverageResources:'Recursos registrados',coverageSources:'Fuentes incorporadas',coverageLoaded:'Hay datos cargados',coverageNotLoaded:'Sin datos cargados',coverageOther:'Otras fuentes',coverageNoAttempt:'Sin intento registrado',coverageLastAttempt:'Último intento',coverageReference:'Referencia del dato',coverageAttemptDate:'Fecha del intento',coverageNeverComplete:'Una importación exitosa no certifica la integridad de la fuente.',coverageTerritory:'Catálogo por territorio',coverageSourceFilter:'Fuente del catálogo',coverageStateFilter:'Estado del catálogo',coverageState:'Estado',coverageAll:'Todos',coverageNoPartitions:'No hay registros cargados con estos criterios.',coverageImports:'Historial de importaciones',coverageImportSource:'Fuente de importaciones',coverageImportStatus:'Resultado de importaciones',coverageImportsError:'No se pudo cargar el historial. La cobertura anterior sigue disponible.',coverageImportsRetry:'Reintentar historial',coverageImportsEmpty:'No hay intentos registrados con estos filtros.',coverageCompleted:'Completada',coveragePartial:'Parcial',coverageFailed:'No publicada',coverageRunning:'En curso',coverageUnknown:'Registro oficial',coverageRead:'Registros leídos',coverageCreated:'Registros creados',coverageUpdated:'Registros modificados',coverageFailedNote:'Los registros anteriores se conservaron; este intento no representa nuevos datos publicados.',coverageHistoryPage:'Página del historial',coverageObservedAt:'Consulta de esta instalación',coverageRecords:'Registros',coverageUnknownState:'Estado no identificado',coverageDocumentation:'Documentación de la fuente',coverageMore:'Detalles por estado'}
 };
 export function sourceLabel(value,t){return Object.hasOwn(labels,value)?labels[value]:t('coverageOther');}
 export function statusLabel(value,t){const keys={completed:'coverageCompleted',partial:'coveragePartial',failed:'coverageFailed',running:'coverageRunning'};return t(Object.hasOwn(keys,value)?keys[value]:'coverageUnknown');}
 export function coverageCount(value,locale,t){return Number.isSafeInteger(value)&&value>=0?value.toLocaleString(locale):t('coverageUnknown');}
export function partitionSelection(rows,source='all',state='all'){
 return rows.filter(row=>(source==='all'||row.source_id===source)&&(state==='all'||row.state===state));
}
