import {StrictMode, useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {api, downloadJSON} from './api';
import {translate, money, safeReference} from './i18n.mjs';
import MapView from './Map';
import type {Detail, Locale, Money, Observation, Place, Source, User} from './types';
import './style.css';

type Town = {id:string;name:string;state:string};
type History = {at:string;type:string;fields:string[];before:Place|null;after:Place};
type Coverage = {municipalities:number;partitions:{dataset:string;state:string;records:number;geocoded:number}[];runs:{id:string;dataset:string;status:string;counts:Record<string,number>}[]};
type Config = {registration_enabled:boolean;source_code:string;revision:string};
const states='AC AL AP AM BA CE DF ES GO MA MT MS MG PA PB PR PE PI RJ RN RS RO RR SC SP SE TO'.split(' ');
const ref=(id:string)=>encodeURIComponent(id);
const getStored=(key:string, fallback:unknown)=>{try{return JSON.parse(localStorage.getItem(key)||'null')??fallback;}catch{return fallback;}};

function App(){
  const [locale,setLocale]=useState<Locale>(()=>{const x=getStored('bdt:locale','pt-BR');return ['pt-BR','en','es'].includes(x)?x:'pt-BR';});
  const t=(key:string)=>translate(locale,key);
  const [view,setView]=useState('explore'),[query,setQuery]=useState(''),[kind,setKind]=useState(''),[state,setState]=useState(''),[town,setTown]=useState(''),[bbox,setBbox]=useState('');
  const [towns,setTowns]=useState<Town[]>([]),[places,setPlaces]=useState<Place[]>([]),[page,setPage]=useState(1),[total,setTotal]=useState(0);
  const [busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[detail,setDetail]=useState<Detail|null>(null),[history,setHistory]=useState<History[]>([]);
  const [user,setUser]=useState<User|null>(null),[config,setConfig]=useState<Config|null>(null),[coverage,setCoverage]=useState<Coverage|null>(null);
  const [favorites,setFavorites]=useState<string[]>(()=>{const x=getStored('bdt:favorites',[]);return Array.isArray(x)?x.filter((v:unknown)=>typeof v==='string'):[];});
  const [saved,setSaved]=useState<Place[]>([]),[mine,setMine]=useState<Observation[]>([]),[queue,setQueue]=useState<Observation[]>([]);
  const [region,setRegion]=useState<{municipality:Town;events:Money[];total:number;truncated:boolean}|null>(null);
  const [tab,setTab]=useState('service');
  const searchVersion=useRef(0),detailVersion=useRef(0);
  function failure(){setNotice('failure');}
  useEffect(()=>{document.documentElement.lang=locale;try{localStorage.setItem('bdt:locale',JSON.stringify(locale));}catch{}},[locale]);
  useEffect(()=>{api<Config>('/config').then(setConfig).catch(failure);api<User>('/auth/me').then(setUser).catch(()=>{});},[]);
  useEffect(()=>{let active=true;api<Town[]>('/municipalities'+(state?'?state='+state:'')).then(x=>{if(active)setTowns(x);}).catch(failure);return()=>{active=false;};},[state]);
  useEffect(()=>{if(view!=='explore')return;const id=++searchVersion.current;const timer=setTimeout(()=>{
    setBusy(true);const params=new URLSearchParams({q:query,kind,state,municipality_id:town,page:String(page),limit:'30'});for(const[k,v]of [...params])if(!v)params.delete(k);if(bbox)params.set('bbox',bbox);
    api<{items:Place[];total:number}>('/places?'+params).then(x=>{if(id===searchVersion.current){setPlaces(x.items);setTotal(x.total);}}).catch(()=>{if(id===searchVersion.current)failure();}).finally(()=>{if(id===searchVersion.current)setBusy(false);});
  },220);return()=>{clearTimeout(timer);searchVersion.current++;};},[query,kind,state,town,bbox,page,view]);
  useEffect(()=>{if(view!=='saved')return;let active=true;Promise.allSettled(favorites.map(id=>api<Detail>('/places/'+ref(id)))).then(rows=>{if(active)setSaved(rows.flatMap(r=>r.status==='fulfilled'?[r.value.place]:[]));});return()=>{active=false;};},[view,favorites]);
  async function navigate(next:string){setView(next);setDetail(null);setRegion(null);setNotice('');detailVersion.current++;
    if(next==='coverage')try{setCoverage(await api<Coverage>('/coverage'));}catch{failure();}
    if(next==='account'&&user)try{setMine(await api<Observation[]>('/observations/mine'));}catch{failure();}
    if(next==='review')try{setQueue(await api<Observation[]>('/review'));}catch{failure();}
  }
  async function select(id:string){const version=++detailVersion.current;setBusy(true);setTab('service');setNotice('');try{const[d,h]=await Promise.all([api<Detail>('/places/'+ref(id)),api<History[]>('/places/'+ref(id)+'/history')]);if(version===detailVersion.current){setDetail(d);setHistory(h);}}catch{failure();}finally{setBusy(false);}}
  function favorite(id:string){const next=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];setFavorites(next);try{localStorage.setItem('bdt:favorites',JSON.stringify(next));}catch{setNotice('blockedStorage');}}
  async function openRegion(id:string){try{setRegion(await api('/regions/'+id));setDetail(null);setView('region');}catch{failure();}}
  function SourceView({source}:{source:Source}){const url=safeReference(source.url);return <div className="source"><span className="eyebrow">{t('source')}</span><strong>{source.dataset}</strong><dl><dt>{t('reference')}</dt><dd>{source.reference_date||t('unknown')}</dd><dt>{t('collected')}</dt><dd>{new Date(source.collected_at).toLocaleDateString(locale)}</dd></dl>{url&&<a href={url} target="_blank" rel="noopener noreferrer">{t('sourceOriginal')} ↗</a>}<details><summary>SHA-256</summary><code>{source.snapshot_sha256}</code></details></div>;}
  function MoneyCards({events}:{events:Money[]}){return events.length?<div className="money-grid">{events.map((e,i)=><article className="money" key={e.source.dataset+e.id+i}><span className="pill">{t(e.phase)}</span><h3>{money(e.cents,locale)}</h3><dl><dt>{t('instrument')}</dt><dd>{e.instrument_id}</dd><dt>{t('recipient')}</dt><dd>{e.recipient}</dd><dt>{t('period')}</dt><dd>{e.period}</dd></dl><SourceView source={e.source}/></article>)}</div>:<p className="empty">{t('financeEmpty')}</p>;}
  function Cards({items}:{items:Place[]}){return <div className="place-list">{items.map(p=><article className="place-card" key={p.id}><div className={'kind-icon '+p.kind} aria-hidden="true">{p.kind==='school'?'▤':p.kind==='health'?'+':'◇'}</div><div><span className="eyebrow">{t(p.kind)} · {p.state}</span><h2><button className="text-button" onClick={()=>select(p.id)}>{p.name}</button></h2><p>{p.address||t('noAddress')}</p><small>{p.source.dataset} · {p.source.reference_date||t('unknown')}</small>{p.latitude===null&&<small className="quiet">{t('noGeo')}</small>}</div><button className="save-icon" aria-label={t(favorites.includes(p.id)?'unsave':'save')+' '+p.name} aria-pressed={favorites.includes(p.id)} onClick={()=>favorite(p.id)}>{favorites.includes(p.id)?'★':'☆'}</button></article>)}</div>;}
  function ObservationCards({rows}:{rows:Observation[]}){return <div className="observations">{rows.map(o=><article key={o.id}><span className="pill">{t(o.status==='pending'?'pendingLabel':o.status)}</span><p>{o.observation.body}</p><small>{t(o.observation.mode)} · {o.observation.observed_on}</small>{safeReference(o.observation.reference_url)&&<p><a href={safeReference(o.observation.reference_url)!} target="_blank" rel="noopener noreferrer">{t('referenceUrl')} ↗</a></p>}</article>)}</div>;}
  async function authentication(event:React.FormEvent<HTMLFormElement>,register=false){event.preventDefault();const data=new FormData(event.currentTarget);setBusy(true);setNotice('');try{const body=JSON.stringify({username:data.get('username'),password:data.get('password')});if(register){await api('/auth/register',{method:'POST',body});setNotice('registered');}else{setUser(await api<User>('/auth/login',{method:'POST',body}));setMine(await api('/observations/mine'));}}catch{failure();}finally{setBusy(false);}}
  async function submitObservation(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!detail)return;const form=event.currentTarget,data=new FormData(form);setBusy(true);try{await api('/observations',{method:'POST',body:JSON.stringify({place_id:detail.place.id,mode:data.get('mode'),observed_on:data.get('observed_on'),body:data.get('body'),reference_url:data.get('reference_url')||null,consent:data.get('consent')==='on'})});setNotice('pending');form.reset();}catch{failure();}finally{setBusy(false);}}
  async function review(event:React.FormEvent<HTMLFormElement>,id:string){event.preventDefault();const data=new FormData(event.currentTarget);try{await api('/review/'+id,{method:'POST',body:JSON.stringify({decision:data.get('decision'),note:data.get('note')})});setQueue(await api('/review'));}catch{failure();}}
  const current=detail?.place;
  return <><a className="skip" href="#main">{t('explore')}</a><header className="header"><button className="brand" onClick={()=>navigate('explore')} aria-label="Brasil de Todos"><span className="brand-mark" aria-hidden="true">✳</span><span>Brasil<span className="brand-sub">de Todos</span></span></button><nav aria-label="Principal">{['explore','saved','coverage'].map(v=><button key={v} className={view===v?'active':''} onClick={()=>navigate(v)}>{t(v)}</button>)}</nav><div className="header-right"><select aria-label="Idioma / Language / Idioma" value={locale} onChange={e=>setLocale(e.target.value as Locale)}><option value="pt-BR">PT</option><option value="en">EN</option><option value="es">ES</option></select><button onClick={()=>navigate('account')}>{user?.username||t('account')}</button>{user?.role==='reviewer'&&<button onClick={()=>navigate('review')}>{t('review')}</button>}</div></header>
  <main id="main">{notice&&<div className="notice" role="status">{t(notice)}<button aria-label={t('close')} onClick={()=>setNotice('')}>×</button></div>}
  {current&&detail?<section className="detail"><button onClick={()=>{setDetail(null);detailVersion.current++;}} className="back">← {t('back')}</button><div className="detail-title"><div><span className="eyebrow">{t(current.kind)} · {current.state}</span><h1>{current.name}</h1><p>{current.address||t('noAddress')}</p></div><button className="primary" aria-pressed={favorites.includes(current.id)} onClick={()=>favorite(current.id)}>{t(favorites.includes(current.id)?'unsave':'save')}</button></div>{!current.catalogue_eligible&&<p className="callout">{t('withdrawn')}</p>}<div className="tabs">{['service','finance','history','community','source'].map(v=><button key={v} className={tab===v?'active':''} onClick={()=>setTab(v)}>{t(v==='service'?'details':v)}</button>)}</div>
  {tab==='service'&&<div className="detail-columns"><article className="panel"><p className="callout">{t('serviceNote')}</p><h2>{t('details')}</h2>{current.phone&&<p>{current.phone}</p>}<div className="tags">{current.declared_services.map(s=><span className="pill" key={s}>{t(s)}</span>)}</div>{current.latitude===null&&<p>{t('noGeo')}</p>}<button onClick={()=>openRegion(current.municipality_id)}>{t('region')} →</button></article><SourceView source={current.source}/></div>}
  {tab==='finance'&&<><p className="callout">{t('regionNote')}</p><MoneyCards events={detail.finance}/><button onClick={()=>openRegion(current.municipality_id)}>{t('region')} →</button></>}
  {tab==='source'&&<><SourceView source={current.source}/><button onClick={()=>downloadJSON('brasildetodos-'+current.id.replace(':','-')+'.json',detail)}>{t('exportData')}</button></>}
  {tab==='history'&&<div className="timeline">{history.length?history.map((h,i)=><article key={h.at+i}><span className="eyebrow">{new Date(h.at).toLocaleString(locale)}</span><h2>{t(h.type)}</h2>{h.type==='updated'&&<><p>{h.fields.join(', ')}</p><details><summary>{t('source')}</summary><pre>{JSON.stringify({before:h.before,after:h.after},null,2)}</pre></details></>}</article>):<p>{t('historyEmpty')}</p>}</div>}
  {tab==='community'&&<><h2>{t('community')}</h2>{detail.observations.length?<ObservationCards rows={detail.observations}/>:<p>{t('noCommunity')}</p>}<div className="panel"><h2>{t('contribute')}</h2><p>{t('observationNote')}</p>{!user?<button onClick={()=>navigate('account')}>{t('login')}</button>:<form onSubmit={submitObservation}><label>{t('mode')}<select name="mode" required><option value="field">{t('field')}</option><option value="document">{t('document')}</option><option value="street_image">{t('street_image')}</option></select></label><label>{t('when')}<input name="observed_on" type="date" required max={new Date().toISOString().slice(0,10)}/></label><label>{t('observation')}<textarea name="body" minLength={20} maxLength={1200} required rows={4}/></label><label>{t('referenceUrl')}<input type="url" name="reference_url" maxLength={2000}/></label><label className="check"><input type="checkbox" name="consent" required/>{t('consent')}</label><button className="primary" disabled={busy}>{t('submit')}</button></form>}</div></>}
  </section>:<>
  {view==='explore'&&<><section className="hero"><span className="eyebrow">BRASIL DE TODOS · OPEN SOURCE</span><h1>{t('tagline')}</h1><p>{t('intro')}</p></section><section className="filters" aria-label={t('search')}><label className="search-label"><span>{t('search')}</span><input type="search" placeholder={t('search')} value={query} maxLength={200} onChange={e=>{setQuery(e.target.value);setPage(1);}}/></label><label><span>{t('states')}</span><select value={state} onChange={e=>{setState(e.target.value);setTown('');setBbox('');setPage(1);}}><option value="">{t('states')}</option>{states.map(s=><option key={s}>{s}</option>)}</select></label><label><span>{t('towns')}</span><select value={town} onChange={e=>{setTown(e.target.value);setBbox('');setPage(1);}}><option value="">{t('towns')}</option>{towns.map(c=><option key={c.id} value={c.id}>{c.name} · {c.state}</option>)}</select></label><button onClick={()=>{setQuery('');setTown('');setState('');setKind('');setBbox('');setPage(1);}}>{t('clear')}</button></section><div className="category-tabs">{['','school','health','work'].map(k=><button key={k} aria-pressed={kind===k} className={kind===k?'selected':''} onClick={()=>{setKind(k);setPage(1);}}>{t(k||'all')}</button>)}</div><div className="explorer"><section aria-live="polite" aria-busy={busy}><div className="results-heading"><strong>{busy?t('loading'):total.toLocaleString(locale)+' '+t('records')}</strong>{bbox&&<button onClick={()=>setBbox('')}>{t('clear')} ⌖</button>}</div>{places.length?<Cards items={places}/>:!busy&&<div className="empty"><h2>{t('empty')}</h2><p>{t('emptyHelp')}</p><button onClick={()=>navigate('coverage')}>{t('coverage')}</button></div>}<div className="pager"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>{t('prev')}</button><span>{page}</span><button disabled={page*30>=total} onClick={()=>setPage(p=>p+1)}>{t('next')}</button></div></section><MapView places={places} select={select} t={t} onBounds={bounds=>{setBbox(bounds);setPage(1);}}/></div></>}
  {view==='saved'&&<section className="page"><h1>{t('saved')}</h1><p className="callout">{t('savedNote')}</p>{saved.length?<Cards items={saved}/>:<p className="empty">{t('empty')}</p>}</section>}
  {view==='region'&&region&&<section className="page"><h1>{t('regionTitle')} · {region.municipality.name}</h1><p className="callout">{t('regionNote')}</p><p>{region.events.length} / {region.total} {t('records')}</p><MoneyCards events={region.events}/></section>}
  {view==='coverage'&&<section className="page"><h1>{t('coverage')}</h1><p className="callout">{t('coverageNote')}</p>{coverage?<><div className="stat"><strong>{coverage.municipalities.toLocaleString(locale)}</strong><span>{t('municipalities')}</span></div>{coverage.partitions.length?<div className="table-scroll"><table><thead><tr><th>{t('source')}</th><th>UF</th><th>{t('records')}</th><th>{t('geocoded')}</th></tr></thead><tbody>{coverage.partitions.map(p=><tr key={p.dataset+p.state}><td>{p.dataset}</td><td>{p.state}</td><td>{p.records}</td><td>{p.geocoded}</td></tr>)}</tbody></table></div>:<p>{t('noneLoaded')}</p>}<h2>{t('runs')}</h2>{coverage.runs.map(r=><article className="panel" key={r.id}><h3>{r.dataset}</h3><code>{r.status}</code><pre>{JSON.stringify(r.counts,null,2)}</pre></article>)}</>:<p>{t('loading')}</p>}</section>}
  {view==='account'&&<section className="page narrow"><h1>{t('account')}</h1><p>{t('authNote')}</p>{user?<><p><strong>{user.username}</strong></p><button onClick={async()=>{try{await api('/auth/logout',{method:'POST'});setUser(null);setMine([]);}catch{failure();}}}>{t('logout')}</button><h2>{t('myContributions')}</h2><ObservationCards rows={mine}/></>:<form className="panel" onSubmit={authentication}><label>{t('username')}<input name="username" autoComplete="username" pattern="[a-zA-Z0-9_-]{3,40}" required/></label><label>{t('password')}<input name="password" type="password" autoComplete="current-password" minLength={12} maxLength={128} required/></label><button className="primary" disabled={busy}>{t('login')}</button>{config?.registration_enabled?<button disabled={busy} type="button" onClick={e=>{const form=e.currentTarget.form;if(form?.reportValidity())authentication({preventDefault(){},currentTarget:form} as React.FormEvent<HTMLFormElement>,true);}}>{t('register')}</button>:<p>{t('registrationOff')}</p>}</form>}</section>}
  {view==='review'&&user?.role==='reviewer'&&<section className="page"><h1>{t('review')}</h1>{queue.length?queue.map(o=><article className="panel" key={o.id}><button onClick={()=>select(o.place_id)}>{o.place_id}</button><ObservationCards rows={[o]}/><form onSubmit={e=>review(e,o.id)}><label>{t('reviewNote')}<textarea required name="note" minLength={10} maxLength={1000}/></label><select name="decision" aria-label={t('review')}><option value="approved">{t('approve')}</option><option value="rejected">{t('reject')}</option></select><button className="primary">{t('submit')}</button></form></article>):<p>{t('noReview')}</p>}</section>}
  </>}
  </main><footer><div><strong>Brasil de Todos</strong><p>{t('independent')}</p></div><div><a href={safeReference(config?.source_code)||'https://github.com/rafaelob/brasildetodos'} target="_blank" rel="noopener noreferrer">{t('code')} ↗</a><p>AGPL-3.0-or-later · {t('noLLM')}</p></div></footer></>;
}
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
