export const actionMessages={
  'pt-BR':{resourceShare:'Compartilhar esta consulta',resourceShareRecord:'Compartilhar este recurso',
    resourceShareHint:'O link inclui o texto da busca e os filtros escolhidos. Confira antes de compartilhar.',
    resourceCopy:'Copiar link',resourceCopied:'Link copiado.',resourceCopyFallback:'Não foi possível copiar automaticamente. Selecione e copie o link.',
    resourceLink:'Link para compartilhar',resourceDownload:'Exportar resumo público',resourceDownloadText:'Resumo em texto',
    resourceClear:'Limpar filtros',resourceFocus:'Recurso compartilhado',resourceBack:'Voltar à consulta',
    resourceFocusMissing:'O recurso compartilhado não está disponível nesta instalação.',resourceResults:'Registros encontrados nesta consulta',
    resourceExportNotice:'Exporta somente metadados públicos, com fonte e valores separados. Não inclui suas contribuições nem documentos privados.',
    resourceEyebrow:'Informação pública, com contexto',resourceNoResults:'Nenhum recurso encontrado com estes filtros.',
    resourceNoResultsHelp:'Isso não significa ausência de obras ou investimentos. Altere a busca ou consulte a cobertura das fontes.'},
  en:{resourceShare:'Share this search',resourceShareRecord:'Share this resource',
    resourceShareHint:'The link includes your search text and selected filters. Check it before sharing.',
    resourceCopy:'Copy link',resourceCopied:'Link copied.',resourceCopyFallback:'Automatic copying failed. Select and copy the link.',
    resourceLink:'Link to share',resourceDownload:'Export public summary',resourceDownloadText:'Text summary',
    resourceClear:'Clear filters',resourceFocus:'Shared resource',resourceBack:'Back to search',
    resourceFocusMissing:'The shared resource is unavailable in this installation.',resourceResults:'Records found in this search',
    resourceExportNotice:'Exports public metadata only, with sources and separate amounts. Excludes your contributions and private documents.',
    resourceEyebrow:'Public information, in context',resourceNoResults:'No resources match these filters.',
    resourceNoResultsHelp:'This does not mean there are no works or investments. Change the search or check source coverage.'},
  es:{resourceShare:'Compartir esta consulta',resourceShareRecord:'Compartir este recurso',
    resourceShareHint:'El enlace incluye el texto de búsqueda y los filtros elegidos. Revísalo antes de compartir.',
    resourceCopy:'Copiar enlace',resourceCopied:'Enlace copiado.',resourceCopyFallback:'No se pudo copiar automáticamente. Selecciona y copia el enlace.',
    resourceLink:'Enlace para compartir',resourceDownload:'Exportar resumen público',resourceDownloadText:'Resumen en texto',
    resourceClear:'Limpiar filtros',resourceFocus:'Recurso compartido',resourceBack:'Volver a la consulta',
    resourceFocusMissing:'El recurso compartido no está disponible en esta instalación.',resourceResults:'Registros encontrados en esta consulta',
    resourceExportNotice:'Exporta solo metadatos públicos, con fuentes e importes separados. No incluye tus contribuciones ni documentos privados.',
    resourceEyebrow:'Información pública, con contexto',resourceNoResults:'No hay recursos con estos filtros.',
    resourceNoResultsHelp:'Esto no significa que no existan obras o inversiones. Cambia la búsqueda o consulta la cobertura de las fuentes.'}
};
