// SPDX-License-Identifier: AGPL-3.0-or-later
import {normalizeResourceRoute} from './resource-route.mjs';
export const statusMessages={
  'pt-BR':{title:'Dados carregados por fonte',notice:'Este painel descreve as importações desta instalação, não monitora os portais oficiais nem certifica cobertura nacional.',loaded:'Registros carregados',none:'Ainda não importado',success:'Última importação concluída',failed:'A última importação falhou',running:'Importação em andamento',unknown:'Estado de importação desconhecido',kept:'Os dados anteriormente carregados continuam disponíveis.',date:'Última importação concluída em',failure:'Não foi possível carregar o painel. A pesquisa continua disponível.',retry:'Tentar painel novamente',loading:'Carregando informações',exportTitle:'Exportar esta seleção',exportNotice:'Inclui até 100 registros, em ordem de identificador, não apenas esta página. O arquivo informa o total e eventuais registros não incluídos. Não inclui dados pessoais de usuários ou documentos privados e não soma valores.',text:'Baixar texto da seleção',csv:'Baixar CSV da seleção',json:'Baixar JSON da seleção',preparing:'Preparando arquivo. Você pode cancelar ou alterar os filtros.',cancel:'Cancelar exportação',cancelled:'Exportação cancelada. Nenhum arquivo foi entregue.',ready:'Arquivo preparado.',exportFailed:'Não foi possível exportar. Nenhum arquivo parcial foi entregue.'},
  en:{title:'Data loaded by source',notice:'This panel describes this installation’s imports. It does not monitor official portals or certify national coverage.',loaded:'Loaded records',none:'Not imported yet',success:'Last import completed',failed:'The last import failed',running:'Import in progress',unknown:'Unknown import status',kept:'Previously loaded data remains available.',date:'Last successful import at',failure:'The panel could not load. Search remains available.',retry:'Retry panel',loading:'Loading information',exportTitle:'Export this selection',exportNotice:'Includes up to 100 records in identifier order, not only this page. The file states the total and whether other records were omitted. No private documents or personal account data; amounts are not summed.',text:'Download selection text',csv:'Download selection CSV',json:'Download selection JSON',preparing:'Preparing the file. You can cancel or change the filters.',cancel:'Cancel export',cancelled:'Export cancelled. No file was delivered.',ready:'File prepared.',exportFailed:'Export failed. No partial file was delivered.'},
  es:{title:'Datos cargados por fuente',notice:'Este panel describe las importaciones de esta instalación; no monitorea los portales oficiales ni certifica cobertura nacional.',loaded:'Registros cargados',none:'Aún no importado',success:'Última importación completada',failed:'La última importación falló',running:'Importación en curso',unknown:'Estado desconocido',kept:'Los datos cargados anteriormente siguen disponibles.',date:'Última importación completada el',failure:'No se pudo cargar el panel. La búsqueda sigue disponible.',retry:'Reintentar panel',loading:'Cargando información',exportTitle:'Exportar esta selección',exportNotice:'Incluye hasta 100 registros por identificador, no solo esta página. El archivo indica el total y los registros no incluidos. No incluye documentos privados ni datos personales de cuentas; no suma importes.',text:'Descargar texto de selección',csv:'Descargar CSV de selección',json:'Descargar JSON de selección',preparing:'Preparando el archivo. Puede cancelar o cambiar los filtros.',cancel:'Cancelar exportación',cancelled:'Exportación cancelada. No se entregó ningún archivo.',ready:'Archivo preparado.',exportFailed:'No se pudo exportar. No se entregó un archivo parcial.'}
};
export function statusText(locale,key){return statusMessages[locale]?.[key]??statusMessages['pt-BR'][key]??key;}
export function selectionExportURL(criteria,format,locale){
  if(!['json','text','csv'].includes(format))throw new Error('unsupported_export_format');
  const selected=normalizeResourceRoute({...criteria,locale});
  const params=new URLSearchParams({format,locale:selected.locale,limit:'100'});
  for(const key of ['q','profile','state'])if(selected[key])params.set(key,selected[key]);
  if(selected.municipality)params.set('municipality_id',selected.municipality);
  if(selected.id)throw new Error('use_individual_revision_export');
  return '/api/resource-collection-export?'+params;
}
