import {regionMessages} from './region-text.mjs';
import {coverageMessages} from './coverage-text.mjs';
import {watchMessages} from './watch-i18n.mjs';
import {actionMessages} from './resource-actions.mjs';
import {resourceMessages} from './resource-i18n.mjs';
import {translate} from './i18n.mjs';
import {featureMessages} from './features-i18n.mjs';
export const additionalMessages={
  'pt-BR':{loadingPlace:'Abrindo a ficha do lugar…',cancelPlace:'Cancelar abertura da ficha',groups:'Grupos',placeIdentifier:'Identificador do lugar',observationWithdrawn:'Contribuição retirada pelo autor',skipToContent:'Pular para o conteúdo',recoveryTitle:'Recuperação de conta',recoveryPrepareNote:'Gere um código agora e guarde-o em lugar seguro. Sem este código, a senha não pode ser redefinida. O código aparece uma vez e não é enviado por e-mail.',recoveryShowOnce:'Copie o código agora. Ele não será mostrado de novo.',recoveryGenerate:'Gerar código de recuperação',recoveryRevoke:'Revogar códigos',recoveryUse:'Redefinir senha com código',recoveryCode:'Código de recuperação',recoveryNewPassword:'Nova senha (mínimo 12 caracteres)',recoveryPrepared:'Código gerado. Guarde-o fora deste aparelho.',recoveryRevoked:'Códigos anteriores foram invalidados.',recoveryReset:'Senha redefinida. Entre com a nova senha.',recoveryCurrentPassword:'Senha atual',recoveryConfirmPassword:'Confirme a nova senha',recoveryMismatch:'As senhas não coincidem.',contested:'Pedido de nova revisão',contestNote:'Se a rejeição estiver errada, peça uma nova revisão a outra pessoa. Isto não publica o texto nem acusa ninguém.',contestReason:'Por que a decisão deve ser revista',contestSubmit:'Pedir nova revisão',contestSent:'Pedido enviado. Outra pessoa fará a revisão.'},
  en:{loadingPlace:'Opening place details…',cancelPlace:'Cancel opening place',groups:'Groups',placeIdentifier:'Place identifier',observationWithdrawn:'Contribution withdrawn by author',skipToContent:'Skip to content',recoveryTitle:'Account recovery',recoveryPrepareNote:'Generate a code now and store it safely. Without this code the password cannot be reset. The code is shown once and is not emailed.',recoveryShowOnce:'Copy the code now. It will not be shown again.',recoveryGenerate:'Generate recovery code',recoveryRevoke:'Revoke codes',recoveryUse:'Reset password with code',recoveryCode:'Recovery code',recoveryNewPassword:'New password (at least 12 characters)',recoveryPrepared:'Code generated. Store it off this device.',recoveryRevoked:'Previous codes were invalidated.',recoveryReset:'Password reset. Sign in with the new password.',recoveryCurrentPassword:'Current password',recoveryConfirmPassword:'Confirm new password',recoveryMismatch:'Passwords do not match.',contested:'Re-review requested',contestNote:'If the rejection is wrong, ask someone else to review it. This does not publish the text or accuse anyone.',contestReason:'Why the decision should be reviewed',contestSubmit:'Request a new review',contestSent:'Request sent. Someone else will review it.'},
  es:{loadingPlace:'Abriendo la ficha del lugar…',cancelPlace:'Cancelar apertura de ficha',groups:'Grupos',placeIdentifier:'Identificador del lugar',observationWithdrawn:'Contribución retirada por el autor',skipToContent:'Saltar al contenido',recoveryTitle:'Recuperación de cuenta',recoveryPrepareNote:'Genera un código ahora y guárdalo en un lugar seguro. Sin este código no se puede restablecer la contraseña. El código aparece una vez y no se envía por correo.',recoveryShowOnce:'Copia el código ahora. No se volverá a mostrar.',recoveryGenerate:'Generar código de recuperación',recoveryRevoke:'Revocar códigos',recoveryUse:'Restablecer contraseña con código',recoveryCode:'Código de recuperación',recoveryNewPassword:'Nueva contraseña (mínimo 12 caracteres)',recoveryPrepared:'Código generado. Guárdalo fuera de este dispositivo.',recoveryRevoked:'Los códigos anteriores quedaron invalidados.',recoveryReset:'Contraseña restablecida. Entra con la nueva contraseña.',recoveryCurrentPassword:'Contraseña actual',recoveryConfirmPassword:'Confirme la nueva contraseña',recoveryMismatch:'Las contraseñas no coinciden.',contested:'Nueva revisión pedida',contestNote:'Si el rechazo está equivocado, pida que otra persona lo revise. Esto no publica el texto ni acusa a nadie.',contestReason:'Por qué debe revisarse la decisión',contestSubmit:'Pedir nueva revisión',contestSent:'Pedido enviado. Otra persona hará la revisión.'}
};
export function uiText(locale,key){
  const language=['pt-BR','en','es'].includes(locale)?locale:'pt-BR';
  const token=String(key);
  // Place ineligibility and author withdrawal are different states.
  if(token==='withdrawn')return translate(language,token);
  for(const catalog of [regionMessages[language],coverageMessages[language],watchMessages[language],actionMessages[language],resourceMessages[language],additionalMessages[language],featureMessages[language]]){
    if(Object.hasOwn(catalog,token)&&typeof catalog[token]==='string')return catalog[token];
  }
  const value=translate(language,token);
  return typeof value==='string'?value:token;
}
export {featureMessages};
