// SPDX-License-Identifier: AGPL-3.0-or-later
export const visitText = {
  "pt-BR": {
    "open": "Registrar visita guiada",
    "close": "Fechar roteiro",
    "intro": "Responda perguntas sobre o que você conseguiu observar pessoalmente. Não use imagens antigas como uma visita atual.",
    "sendError": "Não foi possível confirmar o envio. O texto foi mantido. Consulte suas contribuições antes de tentar novamente.",
    "yes": "Sim",
    "no": "Não",
    "unknown": "Não sei",
    "not_applicable": "Não se aplica",
    "date": "Data da visita",
    "note": "Contexto da sua observação",
    "help": "Descreva o que você observou, sem nomes de pacientes, alunos ou outros dados pessoais. Contexto entre 20 e 500 caracteres; resumo completo limitado a 1.200.",
    "consent": "Entendo que isto é uma observação cidadã, não um laudo, e autorizo sua revisão antes da publicação.",
    "submit": "Enviar roteiro para revisão",
    "sending": "Enviando para revisão…",
    "saved": "Roteiro enviado. Suas respostas estão privadas até uma revisão independente.",
    "again": "Registrar outra visita",
    "source": "Referência consultada",
    "authored": "Perguntas do Brasil de Todos, não exigências oficiais.",
    "missing": "Sem referência temporal informada",
    "privateNotice": "Rascunho apenas nesta tela. Não é enviado enquanto você não confirmar.",
    "methodNote": "Observe somente de área pública permitida. O roteiro é um registro pessoal; não certifica funcionamento, segurança ou acessibilidade.",
    "budget": "O resumo ultrapassa 1.200 caracteres. Reduza o contexto antes de enviar.",
    "preview": "Revisar texto que será enviado",
    "publicNotice": "Cópia de uma observação cidadã aprovada para publicação, não laudo oficial. Respostas, perguntas e contexto foram enviados como texto pelo cidadão. A situação exibida vale para a consulta realizada; cópias já baixadas não podem ser revogadas.",
    "export": "Baixar observação publicada",
    "text": "Texto",
    "json": "JSON",
    "summary": "Respostas estruturadas",
    "context": "Identificador do lugar"
  },
  "en": {
    "open": "Record a guided visit",
    "close": "Close guide",
    "intro": "Answer questions about what you observed in person. Do not use historical images as a current visit.",
    "sendError": "Submission could not be confirmed. Your text was kept. Check your contributions before trying again.",
    "yes": "Yes",
    "no": "No",
    "unknown": "Unknown",
    "not_applicable": "Not applicable",
    "date": "Visit date",
    "note": "Observation context",
    "help": "Describe what you observed, without patient or student names or other personal data. Context between 20 and 500 characters; complete summary limited to 1,200.",
    "consent": "I understand this is a citizen observation, not an expert assessment, and authorize review before publication.",
    "submit": "Submit guide for review",
    "sending": "Submitting for review…",
    "saved": "Guide submitted. Your answers remain private until independent review.",
    "again": "Record another visit",
    "source": "Reference consulted",
    "authored": "Questions authored by Brasil de Todos, not official requirements.",
    "missing": "No reference date provided",
    "privateNotice": "Draft on this screen only. Nothing is submitted until you confirm.",
    "methodNote": "Observe only from a permitted public area. This guide records personal observations; it does not certify operation, safety or accessibility.",
    "budget": "The summary exceeds 1,200 characters. Shorten the context before submitting.",
    "preview": "Review the text to be submitted",
    "publicNotice": "Copy of a citizen observation approved for publication, not an official assessment. Answers, questions and context were submitted as citizen text. Publication status is the status of the retrieved copy; downloaded copies cannot be revoked.",
    "export": "Download published observation",
    "text": "Text",
    "json": "JSON",
    "summary": "Structured answers",
    "context": "Place identifier"
  },
  "es": {
    "open": "Registrar visita guiada",
    "close": "Cerrar guía",
    "intro": "Responda preguntas sobre lo que observó personalmente. No use imágenes históricas como una visita actual.",
    "sendError": "No se pudo confirmar el envío. Se conservó el texto. Consulte sus contribuciones antes de intentarlo de nuevo.",
    "yes": "Sí",
    "no": "No",
    "unknown": "No sé",
    "not_applicable": "No se aplica",
    "date": "Fecha de la visita",
    "note": "Contexto de la observación",
    "help": "Describa lo observado sin nombres de pacientes, estudiantes ni otros datos personales. Contexto entre 20 y 500 caracteres; resumen completo limitado a 1.200.",
    "consent": "Entiendo que esto es una observación ciudadana, no un informe técnico, y autorizo su revisión antes de publicarla.",
    "submit": "Enviar guía para revisión",
    "sending": "Enviando para revisión…",
    "saved": "Guía enviada. Las respuestas son privadas hasta una revisión independiente.",
    "again": "Registrar otra visita",
    "source": "Referencia consultada",
    "authored": "Preguntas de Brasil de Todos, no requisitos oficiales.",
    "missing": "Sin fecha de referencia informada",
    "privateNotice": "Borrador solo en esta pantalla. No se envía hasta que usted confirme.",
    "methodNote": "Observe solo desde un espacio público permitido. Esta guía registra observaciones personales; no certifica funcionamiento, seguridad ni accesibilidad.",
    "budget": "El resumen supera los 1.200 caracteres. Reduzca el contexto antes de enviar.",
    "preview": "Revisar el texto que se enviará",
    "publicNotice": "Copia de una observación ciudadana aprobada para publicación, no informe oficial. Las respuestas, preguntas y contexto se enviaron como texto del ciudadano. El estado corresponde a la consulta realizada; las copias descargadas no pueden revocarse.",
    "export": "Descargar observación publicada",
    "text": "Texto",
    "json": "JSON",
    "summary": "Respuestas estructuradas",
    "context": "Identificador del lugar"
  }
};
